# Generated by Django 5.0.1 on 2024-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postno', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=600)),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
    ]
