# Generated by Django 5.0.1 on 2024-02-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookedshows'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedshows',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookedshows',
            name='seats_remaining',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookedshows',
            name='showID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookedshows',
            name='showname',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookedshows',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
