# Generated by Django 5.0.1 on 2024-02-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookedshows_place_bookedshows_seats_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showname', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showsavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showname', models.TextField(max_length=100, null=True)),
                ('place', models.TextField(null=True)),
                ('time', models.TimeField(default='00:00:00')),
                ('seats_remaining', models.PositiveIntegerField(null=True)),
                ('showID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shows')),
            ],
        ),
        migrations.AlterField(
            model_name='bookedshows',
            name='showID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.showsavailable'),
        ),
    ]
