# Generated by Django 5.0.1 on 2024-02-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_shows_showsavailable_alter_bookedshows_showid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsavailable',
            name='showID',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
