# Generated by Django 5.0.1 on 2024-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_showsavailable_showid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
