# Generated by Django 5.0.1 on 2024-02-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_item_type_item_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.FileField(null=True, upload_to='../uploads/'),
        ),
    ]
