# Generated by Django 5.0.1 on 2024-02-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registermodel',
        ),
    ]
