# Generated by Django 5.0.1 on 2024-02-11 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_loginmodel_remove_bookedshows_showid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(null=datetime.datetime(2024, 2, 11, 7, 6, 28, 690924)),
        ),
    ]
