# Generated by Django 5.0.1 on 2024-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_item_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedshows',
            name='fundraiser',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='showsavailable',
            name='fundraiser',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
